services:
  - type: worker
    name: maythusharv3
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro
    region: oregon
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    envVars:
      - key: API_ID
        value: "23596049"
      - key: API_HASH
        value: "62c2019123d852fc8cc2092ca879f31c"
      - key: BOT_TOKEN
        value: "7892011487:AAEgqHEy3x9TUgZ7i9LZaaz4vDO6v3Pv0EU"
      - key: MONGO_DB_URI
        value: "mongodb+srv://wanglin:wanglin@wanglin.ppt93bd.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "6940535380"
      - key: LOGGER_ID
        value: "-1001901470191"
      - key: COOKIE_URL
        value: "https://batbin.me/minahassian"
      - key: STRING_SESSION
        value: "BQFoDBEAYS9dupvNsr9g-NCgC9kWsP1Xso8-_VtKgLQ-tyn-sxhHp_qfcPbMEz_GP_JUHNPFN_yz3G8CCTIxW6nPBybJTcdFctoC9S9BS1lpOpYLYban_SqiazFOs-YwNNlk167fSb9FKJjHKgzhPbKyOeWr3fVHBRASNE0JPU6Q5c6GqdkP9xlWUmAi4tpoZ9BQ3-b-_iYxiRAKjEVB_VfDq-ZgqwsLdu_tUVSFYRxbiBq7xVVhhLl3GRxLtqovkBtpKvzGFyD7_IRiZJZB3iP1E3cJ2G1bbYCKHx7uNo1mQJV1dPZXMGIOONcwWHL_fIXLvD8VHHmGgeT1yoGtV1iRzWHVSwAAAAFQk4y9AA"
